# Création du build VueJS
FROM node:16-alpine as build-stage
COPY ./package.json /TP1/package.json
WORKDIR /TP1/
RUN npm install
COPY . /TP1/
RUN npm run build

# Création du serveur nginx
FROM nginx:1.24.0-alpine as production-stage
COPY --from=build-stage /TP1/dist /usr/share/nginx/html