# Création du build Angular
FROM node:18-alpine as build-stage
RUN npm i -g @angular/cli
COPY ./package.json /TP1/package.json
WORKDIR /TP1/
RUN npm install
COPY . /TP1/
RUN ng build

# Création du serveur nginx
FROM nginx:1.24.0-alpine as production-stage
COPY --from=build-stage /TP1/dist/angular-16-crud /usr/share/nginx/html